# Generated by Django 2.2.4 on 2022-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('mascot', models.CharField(max_length=50)),
                ('division', models.CharField(max_length=20)),
                ('overall_wins', models.IntegerField()),
                ('overall_losses', models.IntegerField()),
                ('conf_wins', models.IntegerField()),
                ('conf_losses', models.IntegerField()),
                ('primary_color', models.CharField(max_length=20)),
                ('secondary_color', models.CharField(max_length=20)),
            ],
        ),
    ]
